- name: Install base packages
  apt: name={{ item }} state=installed
  with_items:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - curl
    - wget
    - python-pip
    - postfix
  tags:
    - packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages

- name: Add external email to /etc/aliases
  shell: 'echo root: sashley29@gmail.com >> /etc/aliases'


